name: 'End Torque Environment'
description: 'Ends a Torque Environment'
author: 'Quali'
inputs:
  space:
    description: 'The Torque space the Environment is running in'
    required: true
  environment_id:
    description: 'The Torque Environment ID to end'
    required: true
  torque_token:
    description: 'A Torque longterm token'
    required: true
  torque_hostname:
    description: 'Alternative Torque server url'
    required: false
    default: portal.qtorque.io
    
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.environment_id }}
    - ${{ inputs.space }}

  env:
    TORQUE_TOKEN: ${{ inputs.torque_token }}
    TORQUE_SPACE: ${{ inputs.space }}
    TORQUE_HOSTNAME: ${{ inputs.torque_hostname }}
    TORQUE_USERAGENT: Torque-Plugin-Github-Start-Environment-Action/v1

branding:
  icon: 'stop-circle'  
  color: 'red'
